name: Compile Arduino Sketch

on:
  workflow_dispatch:
    inputs:
      sketch:
        description: Base64 encoded .ino file
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Show runner info (debug)
        run: |
          echo "Runner: $RUNNER_OS"
          echo "GH Run ID: $GITHUB_RUN_ID"
          echo "Event: $GITHUB_EVENT_NAME"

      - name: Install Arduino CLI
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p bin
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          ./bin/arduino-cli version

      - name: Prepare Arduino core
        shell: bash
        run: |
          set -euxo pipefail
          ./bin/arduino-cli core update-index
          ./bin/arduino-cli core install arduino:avr

      - name: Create sketch from input
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p sketch
          echo "${{ github.event.inputs.sketch }}" | base64 -d > sketch/sketch.ino
          echo "Sketch head:"
          head -n 20 sketch/sketch.ino || true
          echo "Sketch bytes:"
          wc -c sketch/sketch.ino

      - name: Compile (Uno)
        shell: bash
        run: |
          set -euxo pipefail
          ./bin/arduino-cli compile \
            --fqbn arduino:avr:uno \
            --build-path build \
            --export-binaries \
            sketch
          echo "Build outputs:"
          find build -maxdepth 3 -type f -printf "%P\n" || true
          echo "Sketch root (exported binaries):"
          find sketch -maxdepth 2 -type f -printf "%P\n" || true

      - name: Push HEX to Vercel (/api/artifact)
        env:
          VERCEL_PUSH_URL: https://arduino-web-ide.vercel.app/api/artifact
          HOOK_SECRET: ${{ secrets.HOOK_SECRET }}
        shell: bash
        run: |
          set -euxo pipefail

          HEX_PATH="$(find build -type f -name '*.hex' -print -quit)"
          if [ -z "${HEX_PATH:-}" ]; then
            HEX_PATH="$(find sketch -type f -name '*.hex' -print -quit)"
          fi

          if [ -z "${HEX_PATH:-}" ]; then
            echo "No HEX file found!" >&2
            echo "Debug listing (build/):" >&2
            find build -type f -maxdepth 3 -printf "%P\n" >&2 || true
            echo "Debug listing (sketch/):" >&2
            find sketch -type f -maxdepth 3 -printf "%P\n" >&2 || true
            exit 1
          fi

          if base64 --help 2>/dev/null | grep -q -- "-w"; then
            HEX_B64="$(base64 -w0 "$HEX_PATH")"
          else
            HEX_B64="$(base64 "$HEX_PATH" | tr -d '\n')"
          fi

          curl -fsS -X POST "$VERCEL_PUSH_URL" \
            -H "Content-Type: application/json" \
            -H "X-Hook-Secret: $HOOK_SECRET" \
            -d "{\"run_id\":\"${GITHUB_RUN_ID}\",\"hex_b64\":\"${HEX_B64}\"}"

      - name: Done
        run: echo "HEX pushed to Vercel for run ${GITHUB_RUN_ID}"
