name: Compile Arduino Sketch

on:
  workflow_dispatch:
    inputs:
      sketch:
        description: "Base64 encoded sketch"
        required: true
      client_id:
        description: "Client ID to respond to"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VERCEL_PUSH_URL: https://arduino-web-ide.vercel.app/api/artifact
      HOOK_SECRET: ${{ secrets.HOOK_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          mkdir -p ~/.arduino15
          ./bin/arduino-cli config init
          ./bin/arduino-cli core update-index
          ./bin/arduino-cli core install arduino:avr

      - name: Prepare sketch directory
        run: |
          mkdir -p sketch
          echo "${{ github.event.inputs.sketch }}" | base64 -d > sketch/sketch.ino

      - name: Compile sketch
        run: ./bin/arduino-cli compile --fqbn arduino:avr:uno sketch

      - name: Upload to Vercel artifact API
        run: |
          curl -X POST "$VERCEL_PUSH_URL?client_id=${{ github.event.inputs.client_id }}" \
            -H "x-hook-secret: $HOOK_SECRET" \
            --data-binary "@sketch/build/arduino.avr.uno/sketch.hex"
